sim <- exp(rnorm(5000,5,0.5))
f <- function(y,mu,sigma)
1/(y*sqrt(2*pi*sigma^2))*exp(-((log(y)-mu)^2)/(2*sigma^2))
yval <- seq(0,1000,1)
fval <- f(yval,5,0.5)
pdf("graphs/simulation_1.pdf")
hist(sim,prob=T,nclass=50)
lines(yval,fval)
dev.off()
results <- c(mean(sim),var(sim),sd(sim))
